# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
