# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160917_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
