# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160918_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
